id: IBEE49A99
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:37:56+00:00'
last_modified: '2022-06-07T18:18:03.271267+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26010
  title: དགེ་བའི་བཤེས་གཉེན་ཆེན་པོ་དམུ་དགེ་ཐུབ་བསྟན་རྒྱ་མཚོ་སོགས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    008D:
      image_group_id: I5801
      title: ''
      total_pages: 486
      order: 1
      base_file: 008D.txt
    299A:
      image_group_id: I5802
      title: ''
      total_pages: 390
      order: 2
      base_file: 299A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
